# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TileComponentModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='tile_component_tilecomponentmodel', serialize=False, to='cms.CMSPlugin')),
                ('tile_title', models.CharField(max_length=250)),
                ('has_image', models.BooleanField(default=False)),
                ('img_alt_text', models.CharField(blank=True, default=b'', max_length=250)),
                ('image', filer.fields.image.FilerImageField(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name=b'Image')),
                ('link_to_page', models.ForeignKey(blank=True, help_text=b'Specify the page to which this tile will redirect.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tile_component', to='cms.Page')),
            ],
            options={
                'verbose_name': 'Tile Component',
                'verbose_name_plural': 'Tile Component',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
